const express=require("express"),cors=require("cors"),fs=require("fs"),path=require("path");
const app=express(),PORT=process.env.PORT||10000,SECRET=process.env.DUONG_AI_SECRET||"DUONG_AI_SECRET_2026",ADMIN_PIN=process.env.ADMIN_PIN||"2606",DB_FILE=path.join(__dirname,"users.json");
app.use(cors({origin:"*",methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type","Authorization","x-admin-pin"]}));
app.use(express.json({limit:"2mb"}));app.use(express.urlencoded({extended:true}));
let latestSignal=null,history=[],clients=[];
const now=()=>new Date().toISOString();
const addDays=d=>{let x=new Date();x.setDate(x.getDate()+Number(d||30));return x.toISOString().slice(0,10)};
const num=(v,f=null)=>{if(v===undefined||v===null||v==="")return f;let n=Number(v);return Number.isFinite(n)?n:f};
const sig=v=>{let s=String(v||"WAIT").toUpperCase();if(s.includes("SELL"))return"SELL";if(s.includes("BUY"))return"BUY";return"WAIT"};
function defaults(){return[{username:"admin",password:"2606",name:"Master",email:"",phone:"",plan:"vip",status:"active",expire:"2099-12-31",admin:true,createdAt:now()},{username:"vip001",password:"123456",name:"VIP Client",email:"",phone:"",plan:"pro",status:"active",expire:addDays(30),admin:false,createdAt:now()}]}
function load(){try{if(!fs.existsSync(DB_FILE)){let u=defaults();fs.writeFileSync(DB_FILE,JSON.stringify(u,null,2));return u}return JSON.parse(fs.readFileSync(DB_FILE,"utf8"))}catch(e){return defaults()}}
let users=load(); const save=()=>fs.writeFileSync(DB_FILE,JSON.stringify(users,null,2));
const pub=u=>({username:u.username,name:u.name,email:u.email,phone:u.phone,plan:u.plan,status:u.status,expire:u.expire,admin:!!u.admin,createdAt:u.createdAt});
function admin(req,res,next){let p=req.headers["x-admin-pin"]||req.body?.pin||req.query?.pin;if(p!==ADMIN_PIN)return res.status(403).json({ok:false,error:"Forbidden"});next()}
function normalize(b={}){
 let signal=sig(b.signal||b.side||b.actionSignal),flow=num(b.flow??b.cvd??b.volumeFlow??b.smartFlow),delta=num(b.delta??b.powerDelta??b.diffDelta),power=num(b.power??b.diff??b.momentumPower),confidence=num(b.confidence??b.conf??b.score,signal==="WAIT"?55:80),buySell=b.buySell??b.buy_sell??b.ratio??b.buySellRatio??"--",price=num(b.price??b.close??b.bid),rsi=num(b.rsi),ema=num(b.ema);
 let trend=b.trend||(signal==="BUY"?"Bullish":signal==="SELL"?"Bearish":"Neutral"),pressure=b.pressure||(signal==="BUY"?"BUY PRESSURE":signal==="SELL"?"SELL PRESSURE":"NEUTRAL"),liquidity=b.liquidity||(signal==="BUY"?"Sell-side liquidity / reclaim":signal==="SELL"?"Buy-side liquidity / rejection":"Mid-range / waiting");
 return {id:Date.now().toString(),ok:true,symbol:b.symbol||"XAUUSD",signal,setup:b.setup||(signal==="WAIT"?"WAIT":`${signal} READY`),price,timeframe:b.timeframe||b.tf||"M1",score:confidence,confidence,conf:confidence,trend,pressure,liquidity,risk:b.risk||"Medium",action:b.action||"WAIT CONFIRM",rsi,ema,flow,delta,power,buySell,source:b.source||"MT5_EA_BRIDGE",reason:b.reason||`MT5 Smart Flow ${signal}`,receivedAt:now()};
}
function broadcast(s){let data=`data: ${JSON.stringify({type:"signal",payload:s})}\n\n`;clients=clients.filter(r=>{try{r.write(data);return true}catch{return false}})}
app.get("/",(q,r)=>r.json({ok:true,name:"DUONG AI BACKEND V10.3 AUTH + SMART FLOW API",endpoints:["/auth/register","/auth/login","/admin/users","/webhook/tradingview","/api/latest-signal"],latestSignal}));
app.get("/health",(q,r)=>r.json({ok:true,status:"online",users:users.length,time:now()}));
app.post("/auth/register",(req,res)=>{let {username,password,name,email,phone,plan}=req.body||{},u=String(username||phone||"").trim(),p=String(password||"").trim();if(!u||!p)return res.status(400).json({ok:false,error:"Missing username/password"});if(users.find(x=>x.username.toLowerCase()===u.toLowerCase()))return res.status(409).json({ok:false,error:"User already exists"});let user={username:u,password:p,name:name||u,email:email||"",phone:phone||u,plan:plan||"pro",status:"pending",expire:addDays(0),admin:false,createdAt:now()};users.push(user);save();res.json({ok:true,message:"Registered, waiting approval",user:pub(user)})});
app.post("/auth/login",(req,res)=>{let {username,password}=req.body||{},u=users.find(x=>x.username===String(username||"").trim()&&x.password===String(password||"").trim());if(!u)return res.status(401).json({ok:false,error:"Sai tài khoản hoặc mật khẩu"});if(u.status==="pending")return res.status(403).json({ok:false,error:"Tài khoản đang chờ admin duyệt",status:"pending"});if(u.status==="expired"||new Date(u.expire+"T23:59:59")<new Date()){u.status="expired";save();return res.status(403).json({ok:false,error:"Tài khoản đã hết hạn",status:"expired"})}res.json({ok:true,user:pub(u)})});
app.get("/admin/users",admin,(req,res)=>res.json({ok:true,users:users.map(pub)}));
app.post("/admin/user/update",admin,(req,res)=>{let {username,password,name,email,phone,plan,status,days,expire}=req.body||{},u=String(username||"").trim();if(!u)return res.status(400).json({ok:false,error:"Missing username"});let user=users.find(x=>x.username===u);if(!user){user={username:u,password:password||"123456",name:name||u,email:email||"",phone:phone||u,plan:plan||"pro",status:status||"active",expire:expire||addDays(days||30),admin:false,createdAt:now()};users.push(user)}else{if(password)user.password=password;if(name)user.name=name;if(email!==undefined)user.email=email;if(phone!==undefined)user.phone=phone;if(plan)user.plan=plan;if(status)user.status=status;if(expire)user.expire=expire;else if(days)user.expire=addDays(days)}save();res.json({ok:true,user:pub(user)})});
app.post("/admin/user/delete",admin,(req,res)=>{let before=users.length,username=req.body?.username;users=users.filter(u=>u.username!==username||u.admin);save();res.json({ok:true,deleted:before-users.length})});
app.post("/webhook/tradingview",(req,res)=>{try{let b=req.body||{};if(b.secret&&b.secret!==SECRET)return res.status(401).json({ok:false,error:"Invalid secret"});let s=normalize(b);latestSignal=s;history.unshift(s);history=history.slice(0,200);broadcast(s);res.json({ok:true,received:s})}catch(e){res.status(400).json({ok:false,error:"Bad Request",detail:e.message})}});
app.get("/api/latest-signal",(req,res)=>res.json(latestSignal||{ok:true,symbol:"XAUUSD",signal:"WAIT",price:null,timeframe:"M1",score:55,confidence:55,trend:"Neutral",pressure:"NEUTRAL",liquidity:"Mid-range / waiting",risk:"Medium",action:"WAIT CONFIRM",rsi:null,flow:null,delta:null,power:null,buySell:"--",source:"API_IDLE",reason:"Waiting MT5 data",receivedAt:now()}));
app.get("/api/history",(req,res)=>res.json({ok:true,count:history.length,history}));
app.get("/events",(req,res)=>{res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();clients.push(res);res.write(`data: ${JSON.stringify({type:"connected",payload:{ok:true,time:now()}})}\n\n`);if(latestSignal)res.write(`data: ${JSON.stringify({type:"signal",payload:latestSignal})}\n\n`);req.on("close",()=>clients=clients.filter(c=>c!==res))});
app.listen(PORT,()=>console.log("DUONG AI V10.3 AUTH API running on "+PORT));