const API_URL=window.location.origin;
const $=id=>document.getElementById(id);
function set(id,v){const e=$(id); if(e)e.textContent=(v===undefined||v===null||v==='')?'--':v}
function saveSession(user){localStorage.setItem('vyroUser',JSON.stringify(user))}
function getSession(){try{return JSON.parse(localStorage.getItem('vyroUser')||'null')}catch(e){return null}}
function showDash(user){$('loginPage').classList.add('hidden');$('dashboard').classList.remove('hidden');set('accountName',user.name||user.username);set('accountPlan',user.plan||'VIP AI');set('expire',user.expire||'2099-12-31');loadSignal()}
function showLogin(){$('dashboard').classList.add('hidden');$('loginPage').classList.remove('hidden')}
async function login(e){e.preventDefault(); const username=$('username').value.trim(); const password=$('password').value.trim(); $('loginMsg').textContent='Đang đăng nhập...'; try{const r=await fetch(API_URL+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}); const d=await r.json(); if(!d.success&&!d.ok) throw new Error(d.message||'Sai tài khoản hoặc mật khẩu'); saveSession(d.user); $('loginMsg').textContent=''; showDash(d.user)}catch(err){$('loginMsg').textContent=err.message||'Không đăng nhập được'}}
async function loadSignal(){try{const r=await fetch(API_URL+'/api/latest-signal?t='+Date.now(),{cache:'no-store'});const d=await r.json();console.log('VYRO SIGNAL',d);const sig=d.signal||d.status||'WAIT';set('mainSignal',sig);set('symbolValue',d.symbol||'XAUUSD');set('symbolSub',sig);set('rsiValue',d.rsi);set('flowValue',d.flow);set('deltaValue',d.delta);set('powerValue',d.power);set('buySellValue',d.buySell||'0/0');const conf=d.conf||d.confidence||d.score||55;set('confValue',conf+'%');set('aiScore',conf);set('pressureValue',d.pressure||d.raw?.pressure||sig);set('trendValue',d.trend||d.raw?.trend||(sig==='BUY'?'Bullish':sig==='SELL'?'Bearish':'Neutral'));set('liquidityValue',d.liquidity||d.raw?.liquidity||'Waiting');set('riskValue',d.risk||d.raw?.risk||'--');set('actionValue',d.action||d.raw?.action||'--');set('dominanceValue',d.pressure||d.raw?.pressure||'Mixed');set('flowMini',d.flow);set('deltaMini',d.delta);set('powerMini',d.power);set('updateValue',new Date(d.updatedAt||Date.now()).toLocaleTimeString());$('statusText').textContent='API đã nhận dữ liệu realtime từ MT5.'}catch(e){console.error(e)}}
async function testBuy(){await fetch(API_URL+'/api/test-signal',{method:'POST'});loadSignal()}
document.addEventListener('DOMContentLoaded',()=>{$('loginForm').addEventListener('submit',login);$('pullBtn')?.addEventListener('click',loadSignal);$('testBtn')?.addEventListener('click',testBuy);$('logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem('vyroUser');showLogin()});const u=getSession(); if(u)showDash(u); else showLogin();setInterval(()=>{if(!$('dashboard').classList.contains('hidden'))loadSignal()},3000)});